version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:1.23.1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx_network

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.29
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - ../meilisearch/data:/meili_data
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true