version: "3.9"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.15.1
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    environment:
      - VIRTUAL_HOST=portainer-research-rendi.innocentbatman.my.id
      - VIRTUAL_PORT=9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - /etc/letsencrypt/live/portainer-research-rendi.innocentbatman.my.id:/certs/live/portainer-research-rendi.innocentbatman.my.id:ro
      - /etc/letsencrypt/archive/portainer-research-rendi.innocentbatman.my.id:/certs/archive/portainer-research-rendi.innocentbatman.my.id:ro
    command: -H unix:///var/run/docker.sock

  portainer_agent:
    container_name: portainer-agent
    image: portainer/agent:2.15.1
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
