version: "3.3"

services:
  meilisearch:
    image: getmeili/meilisearch:v0.29
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - ./data:/meili_data
